<?php
namespace iadvdm\service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:08.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ServiceError;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iadvdm\service\Error::setFromException
     * @todo   Implement testSetFromException().
     */
    public function testSetFromException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\service\Error::getJsonError
     * @todo   Implement testGetJsonError().
     */
    public function testGetJsonError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\service\Error::logError
     * @todo   Implement testLogError().
     */
    public function testLogError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
