<?php
namespace iadvdm\vdm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:08.
 */
class VdmArticlesParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var VdmArticlesParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VdmArticlesParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::getArticlesFromWeb
     * @todo   Implement testGetArticlesFromWeb().
     */
    public function testGetArticlesFromWeb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::parseArticles
     * @todo   Implement testParseArticles().
     */
    public function testParseArticles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::parseArticleId
     * @todo   Implement testParseArticleId().
     */
    public function testParseArticleId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::parseArticleContent
     * @todo   Implement testParseArticleContent().
     */
    public function testParseArticleContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::parseArticleDate
     * @todo   Implement testParseArticleDate().
     */
    public function testParseArticleDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesParser::parseArticleAuthor
     * @todo   Implement testParseArticleAuthor().
     */
    public function testParseArticleAuthor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
