<?php
namespace iadvdm\vdm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:08.
 */
class VdmArticlesUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var VdmArticlesUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VdmArticlesUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesUtils::find
     * @todo   Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesUtils::orderBy
     * @todo   Implement testOrderBy().
     */
    public function testOrderBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesUtils::merge
     * @todo   Implement testMerge().
     */
    public function testMerge()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
