<?php
namespace iadvdm\vdm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:08.
 */
class VdmArticlesManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var VdmArticlesManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VdmArticlesManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesManager::loadNewArticles
     * @todo   Implement testLoadNewArticles().
     */
    public function testLoadNewArticles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesManager::saveToJsonFile
     * @todo   Implement testSaveToJsonFile().
     */
    public function testSaveToJsonFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesManager::addToJsonFile
     * @todo   Implement testAddToJsonFile().
     */
    public function testAddToJsonFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\vdm\VdmArticlesManager::loadFromJsonFile
     * @todo   Implement testLoadFromJsonFile().
     */
    public function testLoadFromJsonFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
