<?php
namespace iadvdm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:09.
 */
class UtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Utils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers iadvdm\Utils::utf8_encode_object
     * @todo   Implement testUtf8_encode_object().
     */
    public function testUtf8_encode_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers iadvdm\Utils::utf8_decode_object
     * @todo   Implement testUtf8_decode_object().
     */
    public function testUtf8_decode_object()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
