<?php
namespace iadvdm\service\api;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 00:27:08.
 */
class PostTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Post
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Post;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
